# ===========================================
# Pickle Go - Cloud Build 配置
# ===========================================
# 用於自動部署前後端到 GCP Cloud Run
# 觸發條件: push 到 main 分支

substitutions:
  _REGION: asia-east1
  _API_SERVICE_NAME: pickle-go-api
  _WEB_SERVICE_NAME: pickle-go-web
  _CLOUDSQL_INSTANCE: ${PROJECT_ID}:${_REGION}:pickle-go-db

options:
  logging: CLOUD_LOGGING_ONLY
  machineType: E2_HIGHCPU_8

steps:
  # ===========================================
  # Step 1: 建置 API 映像檔
  # ===========================================
  - id: 'build-api'
    name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - '${_REGION}-docker.pkg.dev/${PROJECT_ID}/pickle-go/${_API_SERVICE_NAME}:${SHORT_SHA}'
      - '-t'
      - '${_REGION}-docker.pkg.dev/${PROJECT_ID}/pickle-go/${_API_SERVICE_NAME}:latest'
      - '-f'
      - 'apps/api/Dockerfile'
      - 'apps/api'
    waitFor: ['-']

  # ===========================================
  # Step 2: 建置 Web 映像檔
  # ===========================================
  - id: 'build-web'
    name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - '${_REGION}-docker.pkg.dev/${PROJECT_ID}/pickle-go/${_WEB_SERVICE_NAME}:${SHORT_SHA}'
      - '-t'
      - '${_REGION}-docker.pkg.dev/${PROJECT_ID}/pickle-go/${_WEB_SERVICE_NAME}:latest'
      - '-f'
      - 'apps/web/Dockerfile'
      - 'apps/web'
      - '--build-arg'
      - 'NEXT_PUBLIC_API_URL=https://api.picklego.tw'
      - '--build-arg'
      - 'NEXT_PUBLIC_BASE_URL=https://picklego.tw'
      - '--build-arg'
      - 'NEXT_PUBLIC_LINE_CHANNEL_ID=${_LINE_CHANNEL_ID}'
      - '--build-arg'
      - 'NEXT_PUBLIC_LINE_REDIRECT_URI=https://picklego.tw/auth/callback'
      - '--build-arg'
      - 'NEXT_PUBLIC_GOOGLE_MAPS_API_KEY=${_GOOGLE_MAPS_API_KEY}'
      - '--build-arg'
      - 'NEXT_PUBLIC_SENTRY_DSN=${_SENTRY_DSN_WEB}'
      - '--build-arg'
      - 'NEXT_PUBLIC_GA_MEASUREMENT_ID=${_GA_MEASUREMENT_ID}'
    waitFor: ['-']

  # ===========================================
  # Step 3: 推送 API 映像檔到 Artifact Registry
  # ===========================================
  - id: 'push-api'
    name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - '--all-tags'
      - '${_REGION}-docker.pkg.dev/${PROJECT_ID}/pickle-go/${_API_SERVICE_NAME}'
    waitFor: ['build-api']

  # ===========================================
  # Step 4: 推送 Web 映像檔到 Artifact Registry
  # ===========================================
  - id: 'push-web'
    name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - '--all-tags'
      - '${_REGION}-docker.pkg.dev/${PROJECT_ID}/pickle-go/${_WEB_SERVICE_NAME}'
    waitFor: ['build-web']

  # ===========================================
  # Step 5: 部署 API 到 Cloud Run
  # ===========================================
  - id: 'deploy-api'
    name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - '${_API_SERVICE_NAME}'
      - '--image'
      - '${_REGION}-docker.pkg.dev/${PROJECT_ID}/pickle-go/${_API_SERVICE_NAME}:${SHORT_SHA}'
      - '--region'
      - '${_REGION}'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--add-cloudsql-instances'
      - '${_CLOUDSQL_INSTANCE}'
      - '--set-env-vars'
      - 'ENVIRONMENT=production'
      - '--set-secrets'
      - 'DATABASE_URL=pickle-go-database-url:latest,JWT_SECRET=pickle-go-jwt-secret:latest,LINE_CHANNEL_ID=pickle-go-line-channel-id:latest,LINE_CHANNEL_SECRET=pickle-go-line-channel-secret:latest,SENTRY_DSN=pickle-go-sentry-dsn-api:latest'
      - '--cpu'
      - '1'
      - '--memory'
      - '512Mi'
      - '--min-instances'
      - '0'
      - '--max-instances'
      - '10'
      - '--concurrency'
      - '80'
      - '--timeout'
      - '300s'
    waitFor: ['push-api']

  # ===========================================
  # Step 6: 部署 Web 到 Cloud Run
  # ===========================================
  - id: 'deploy-web'
    name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - '${_WEB_SERVICE_NAME}'
      - '--image'
      - '${_REGION}-docker.pkg.dev/${PROJECT_ID}/pickle-go/${_WEB_SERVICE_NAME}:${SHORT_SHA}'
      - '--region'
      - '${_REGION}'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--cpu'
      - '1'
      - '--memory'
      - '512Mi'
      - '--min-instances'
      - '0'
      - '--max-instances'
      - '10'
      - '--concurrency'
      - '80'
      - '--timeout'
      - '60s'
    waitFor: ['push-web']

# 映像檔列表
images:
  - '${_REGION}-docker.pkg.dev/${PROJECT_ID}/pickle-go/${_API_SERVICE_NAME}:${SHORT_SHA}'
  - '${_REGION}-docker.pkg.dev/${PROJECT_ID}/pickle-go/${_API_SERVICE_NAME}:latest'
  - '${_REGION}-docker.pkg.dev/${PROJECT_ID}/pickle-go/${_WEB_SERVICE_NAME}:${SHORT_SHA}'
  - '${_REGION}-docker.pkg.dev/${PROJECT_ID}/pickle-go/${_WEB_SERVICE_NAME}:latest'

# 逾時設定: 30 分鐘
timeout: 1800s
